### ISSUE TITLE
Travis Builds failed.

### ISSUE THREAD

**Issue by yelinaung** [Rabbit-Converter/Rabbit-Python#2]
@mapmeld Can you take a look at the Travis builds ? 

https://travis-ci.org/Rabbit-Converter/Rabbit-Python/jobs/69681358

https://travis-ci.org/Rabbit-Converter/Rabbit-Python/jobs/69681359

**Comment by mapmeld** [comment]
I had Travis CI test with Python 2.6 and 3.2, which are quite old now. On my machine, I have 2.7 and 3.4. Let's add requirements to the Readme, and update versions in the .travis.yml

**Comment by mapmeld** [comment]
@yelinaung I've installed pyenv so I can get it working on older Python versions, too. I'll do another pull request when I get Travis working with my repo

**Comment by yelinaung** [comment]
Thanks @mapmeld
